version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/patogram/
file_exists_behavior: OVERWRITE
hooks:
  Install:
    - location: setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: root
