version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/patogram_backend/
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: run.sh
      timeout: 300
      runas: root
