version: "3.10"
services:
  backend:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patogram_backend_backend
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/app
